# TASK 4



## 1. Introduction to NumPy
What NumPy is and why it’s important for numerical computations in Python.
Installation of NumPy (pip install numpy).
Understanding its role in data science, machine learning, and scientific computing.



## 
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

 It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## 2. Arrays in NumPy
Understanding the concept of ndarray (N-dimensional array).


# 1-d array

In [21]:
import numpy as np
a = ([1,2,3])
print(a)

[1, 2, 3]


# 2-d array

In [30]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
import numpy # importing numpy library

arr = numpy.array([1,2,3,4])   # defining array
print(arr)                     # print array


[1 2 3 4]


### Using np.zeros().

In [6]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Using np.ones()

In [7]:
import numpy as np
arr = np.ones(9)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Using np.arange()

In [9]:
import numpy as np
arr = np.arange(1,12,3)
print(arr)

[ 1  4  7 10]


### using np.linspace()

In [15]:
import numpy as np
arr = np.linspace(1,10, num=10)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Array Indexing and slicing

In [13]:
import numpy as np
arr = np.array([12,34,43,55,76,87,45,18,63)]  # indexing
print(arr[3])                                 # printing according to index number in arrray list

55


In [14]:
import numpy as np
arr = np.array([12,32,43,54,54])
print(arr[1:3])

[32 43]


# 3. Array Operations
Arithmetic operations on NumPy arrays (addition, subtraction, multiplication, division).
Broadcasting (performing operations on arrays of different shapes).
Element-wise operations and functions (e.g., np.sqrt(), np.sin(), np.exp()).


In [16]:
# addition
#import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = a+b
print(arr)


[5 7 9]


In [17]:
#subsdtarction
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = a-b
print(arr)

[-3 -3 -3]


In [18]:
# division
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = a/b
print(arr)

[0.25 0.4  0.5 ]


# 4. Array Shapes and Reshaping
Checking array dimensions with .shape and .ndim.
Changing array shape with .reshape(), .flatten(), .transpose().
Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().


In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=10)

print(arr)
print('shape of array :', arr.shape)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
shape of array : (1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


#### changing array shape

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])    # changing from 1-D to 2-D

newarr = arr.reshape(4, 3)                                 # using .reshape

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
#.transpose
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

new=np.transpose(arr)
print(new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [44]:
#..flatten
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

new = arr.flatten()
print(new)

[1 2 3 4 5 6 7 8]


###  Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().

In [45]:
#concatinating the array 
#using np.concatenate
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [47]:
# joining the array'
# using np.stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
#joining the array
#using np.vstack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2) )

print(arr)

[[1 2 3]
 [4 5 6]]


In [52]:
# joining the array
# using np.hstack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [54]:
#spliting the array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


# 5. Array Manipulation
Indexing and slicing: understanding multi-dimensional arrays.
Masking (logical indexing based on conditions).
Fancy indexing (using arrays of indices to select elements).


In [57]:
#logical indexing
# Create a 2D NumPy array
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

row_index = np.where(arr == 30)[0][0]
print("Row index of element 30:", row_index)

Row index of element 30: 0


In [58]:
#fancy indexing
import numpy as np

# Create a 2D NumPy array
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.where(arr > 60)[0]
print("Row indices where elements are greater than 60:", row_indices)

Row indices where elements are greater than 60: [2 2 2]


# 6. Mathematical Functions
Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply().
Statistical functions: np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().
Linear algebra functions: np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().



In [59]:
# np.add()
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
new = np.add(a,b)
print(new)

[5 7 9]


In [60]:
# np.subtract
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
new = np.subtract(a,b)
print(new)

[-3 -3 -3]


In [61]:
#np.multiply
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
new = np.multiply(a,b)
print(new)

[ 4 10 18]


In [63]:
# np.median()
import numpy as np
a = np.array([1,2,3])
new = np.median(a)
print(new)

2.0


In [64]:
#np.std
import numpy as np
a = np.array([1,2,3])
new = np.std(a)
print(new)

0.816496580927726


In [65]:
#np.var()
import numpy as np
a = np.array([1,2,3])
new = np.var(a)
print(new)

0.6666666666666666


In [66]:
# np.min()
import numpy as np
a = np.array([1,2,3])
new = np.min(a)
print(new)

1


In [67]:
# np.max()
import numpy as np
a = np.array([1,2,3])
new = np.max(a)
print(new)

3


## linear algebra fuction

In [69]:
#np.matmul()
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.matmul(a, b)
print(result) 


32


In [70]:
#np.dot()
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result)  # Output: 32


32
